# プロジェクト名
name = "landscape-screensaver"

# 静的ファイル配置ディレクトリ
pages_build_output_dir = "public"

# 互換性日付（必須）
compatibility_date = "2025-03-23"

[vars]
UNSPLASH_API_KEY = "H1uksBxyGFRLY6wPRISUjSVSCdwXQ1akYYwIoCIa1hk"
PEXELS_API_KEY = "jCeBbTeVf6shhQtyW7xqY9wgHsTlZ1wSHOpF8DP9L9TIcfQk0fBsmX0r"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "6b12be5619434fba85faf8732767a046"