# wrangler.toml
name = "landscape-screensaver"

# ページの設定
[site]
bucket = "./public"  # 静的ファイルが格納されるディレクトリ

# 環境変数
[vars]
# 開発用（本番環境ではCloudflareダッシュボードで設定）
# UNSPLASH_API_KEY = "unsplashのAPIキーをここに入力"

# KVネームスペース
[[kv_namespaces]]
binding = "UNSPLASH_CACHE"  # バインド名
# id = "xxxx"               # KV名前空間ID（ダッシュボードで確認）
preview_id = "xxxx"         # プレビュー用ID（ダッシュボードで確認）